### ISSUE TITLE
Handle Permissions Events

### ISSUE THREAD

**Issue by rdig** [JoinColony/block-ingestor#12]
Handle the following events to extract required permissions:
- `ColonyRoleSet(indexed address,indexed uint256,indexed uint8,bool)` -- old version of event
- `ColonyRoleSet(address,indexed address,indexed uint256,indexed uint8,bool)` -- current version of event
- `RecoveryRoleSet(indexed address,bool)` -- recovery role

Note to extract domain, and block at which point this permission was set.

A good idea is to look up the way we used to fetch permissions in colonyJS: https://github.com/JoinColony/colonyJS/blob/deprecated/4.x.x-branch-still-in-use/src/helpers.ts#L194-L255

![Image](https://user-images.githubusercontent.com/1193222/215905561-0f8ce7e6-daad-457b-8ee0-4756845e7be8.png)

**Comment by jakubcolony** [comment]
Completed in #60
