### ISSUE TITLE
`motionCreated` handler crashes if staked expenditure extension not installed in colony

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/block-ingestor#139]
As in the title. Presumably the same would happen if OneTxPayment wasn't installed.

This might be a good opportunity to ensure all code related to getting clients uses `~utils/clients` - there's a function for getting a Staked Expenditure client already and we'd need one for OneTxPayment.

**Comment by jakubcolony** [comment]
@willm30 fyi

**Comment by willm30** [comment]
i have fixed this

**Comment by willm30** [comment]
https://github.com/JoinColony/block-ingestor/pull/117/commits/9204029501183d7f0580a25de902a187fa14a1c0

**Comment by jakubcolony** [comment]
Great, will just need to rebase then, thanks 👍
