### ISSUE TITLE
[Verified Members] Update the isVerified flag for contributors when verifying / unverifying members

### ISSUE THREAD

**Issue by iamsamgibbs** [JoinColony/block-ingestor#172]
### Story

In the UI, we display verified checkmarks for users which are added as verified. 
We need to realign this according to the verified members rework.

### Description

This should be done by changing the `isVerified` flag on the `ColonyContributor` model.

### This issue is complete when...

- [ ] The `isVerified` flag and checkmarks reflect the state of verified members after realign

**Comment by rdig** [comment]
@iamsamgibbs since this was added after the planning meeting, please also add an estimate for it. Thanks!

**Comment by bassgeta** [comment]
Closing since it didn't autoclose
