### ISSUE TITLE
Write colony data to the db

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/block-ingestor#6]
Currently we don't write the colony data to the database, meaning we don't have access to all the colonies created before block-ingestor has started and we have to rely on frontend mutating the db directly (which we want to go away from). 

This issue can be split in two parts:
- The `trackColonies` function should be extended to not only set up the colony specific listeners but also write the colony to the database. This is to ensure we store info on all previously created colonies
- Writing colony info to the db when handling `ColonyAdded` event

**Comment by jakubcolony** [comment]
Blocked by https://github.com/JoinColony/colonyCDapp/issues/292

**Comment by willm30** [comment]
@jakubcolony Presume this is closeable.
