### ISSUE TITLE
Write the latest version for colonies (and extensions) to the stats file

### ISSUE THREAD

**Issue by jakubcolony** [JoinColony/block-ingestor#9]
> I think it will be useful to write the latest version for colonies (and extensions) to the stats file as well.
This will help with checks once we get in production.

_Originally posted by @rdig in https://github.com/JoinColony/block-ingestor/pull/4#discussion_r1073768411_

**Comment by willm30** [comment]
Closing as I presume this is done

**Comment by jakubcolony** [comment]
Not done as described in the issue but I don't see value in this anymore, the latest versions can be easily retrieved from the DB for debugging purpose
